export const navLinks = [
  {
    id: 1,
    label: "Início",
    href: "/",
  },
  {
    id: 2,
    label: "Calendário",
    href: "/calendario",
  },
  {
    id: 3,
    label: "Equipa",
    href: "/equipa",
  },
  {
    id: 4,
    label: "Loja",
    href: "/loja",
  },
  {
    id: 5,
    label: "Contacto",
    href: "/contacto",
  },
];

export const sponsors = [
  {
    id: 1,
    name: "JF Azias",
    logo: "/images/sponsors/azias.png",
    website: "https://www.jf-azias.pt",
  },
  {
    id: 2,
    name: "Associação Vontade e Tradição - Azias ",
    logo: "",
    website: "",
  },
  {
    id: 3,
    name: "Restaurante Pizzaria São Sebastião",
    logo: "/images/sponsors/cafe-s-sebastiao.jpg",
    website:
      "https://www.facebook.com/p/Restaurante-Pizzaria-S%C3%A3o-Sebasti%C3%A3o-61561312854116/",
  },
  {
    id: 4,
    name: "Ricardo Pereira",
    logo: "",
    website: "",
  },
  {
    id: 5,
    name: "Varandas do Lima",
    logo: "",
    website: "",
  },
  {
    id: 6,
    name: "Taberna do Alexandre",
    logo: "",
    website: "",
  },
  {
    id: 7,
    name: "Serração da Barca",
    logo: "",
    website: "",
  },
  {
    id: 8,
    name: "Feira dos Pneus",
    logo: "",
    website: "",
  },
  {
    id: 9,
    name: "Carpinóbrega",
    logo: "",
    website: "https://www.facebook.com/carpinobrega/",
  },
];

export const calendar = [
  {
    id: 0,
    match: {
      championship: "Liga INATEL",
      jornada: 1,
      date: "Domingo, 14 Dezembro 2025",
      hour: "12:00",
      address: "Campo da Manguela, AZIAS Ponte da Barca",
      playAtHome: true,
    },
    team: {
      teamPlayingAtHome: "Azias FC",
      teamPlayingAtHomeLogo: "/azias-fc-logo.png",
      teamPlayingAway: "FC Azias",
      teamPlayingAwayLogo: "/azias-fc-logo.png",
    },
    results: {
      teamPlayingAtHomeScore: 2,
      teamPlayingAwayScore: 1,
    },
  },
  {
    id: 1,
    match: {
      championship: "Liga INATEL",
      jornada: 2,
      date: "Domingo, 14 Dezembro 2025",
      hour: "12:00",
      address: "Campo da Manguela, AZIAS Ponte da Barca",
      playAtHome: true,
    },
    team: {
      teamPlayingAtHome: "Azias FC",
      teamPlayingAtHomeLogo: "/azias-fc-logo.png",
      teamPlayingAway: "FC Azias",
      teamPlayingAwayLogo: "/azias-fc-logo.png",
    },
    results: {
      teamPlayingAtHomeScore: 2,
      teamPlayingAwayScore: 1,
    },
  },
  {
    id: 2,
    match: {
      championship: "Liga INATEL",
      jornada: 3,
      date: "Domingo, 14 Dezembro 2025",
      hour: "12:00",
      address: "Campo da Manguela, AZIAS Ponte da Barca",
      playAtHome: true,
    },
    team: {
      teamPlayingAtHome: "Azias FC",
      teamPlayingAtHomeLogo: "/azias-fc-logo.png",
      teamPlayingAway: "FC Azias",
      teamPlayingAwayLogo: "/azias-fc-logo.png",
    },
    results: {
      teamPlayingAtHomeScore: 2,
      teamPlayingAwayScore: 1,
    },
  },
  {
    id: 3,
    match: {
      championship: "Liga INATEL",
      jornada: 4,
      date: "Domingo, 14 Dezembro 2025",
      hour: "12:00",
      address: "Campo da Manguela, AZIAS Ponte da Barca",
      playAtHome: true,
    },
    team: {
      teamPlayingAtHome: "Azias FC",
      teamPlayingAtHomeLogo: "/azias-fc-logo.png",
      teamPlayingAway: "FC Azias",
      teamPlayingAwayLogo: "/azias-fc-logo.png",
    },
    results: {
      teamPlayingAtHomeScore: 2,
      teamPlayingAwayScore: 1,
    },
  },
  {
    id: 4,
    match: {
      championship: "Liga INATEL",
      jornada: 5,
      date: "Domingo, 14 Dezembro 2025",
      hour: "12:00",
      address: "Campo da Manguela, AZIAS Ponte da Barca",
      playAtHome: true,
    },
    team: {
      teamPlayingAtHome: "Azias FC",
      teamPlayingAtHomeLogo: "/azias-fc-logo.png",
      teamPlayingAway: "FC Azias",
      teamPlayingAwayLogo: "/azias-fc-logo.png",
    },
    results: {
      teamPlayingAtHomeScore: 2,
      teamPlayingAwayScore: 1,
    },
  },
  {
    id: 5,
    match: {
      championship: "Liga INATEL",
      jornada: 6,
      date: "Domingo, 14 Dezembro 2025",
      hour: "12:00",
      address: "Campo da Manguela, AZIAS Ponte da Barca",
      playAtHome: true,
    },
    team: {
      teamPlayingAtHome: "Azias FC",
      teamPlayingAtHomeLogo: "/azias-fc-logo.png",
      teamPlayingAway: "FC Azias",
      teamPlayingAwayLogo: "/azias-fc-logo.png",
    },
    results: {
      teamPlayingAtHomeScore: 2,
      teamPlayingAwayScore: 1,
    },
  },
  {
    id: 6,
    match: {
      championship: "Liga INATEL",
      jornada: 7,
      date: "Domingo, 14 Dezembro 2025",
      hour: "12:00",
      address: "Campo da Manguela, AZIAS Ponte da Barca",
      playAtHome: true,
    },
    team: {
      teamPlayingAtHome: "Azias FC",
      teamPlayingAtHomeLogo: "/azias-fc-logo.png",
      teamPlayingAway: "FC Azias",
      teamPlayingAwayLogo: "/azias-fc-logo.png",
    },
    results: {
      teamPlayingAtHomeScore: 2,
      teamPlayingAwayScore: 1,
    },
  },
  {
    id: 7,
    match: {
      championship: "Liga INATEL",
      jornada: 8,
      date: "Domingo, 14 Dezembro 2025",
      hour: "12:00",
      address: "Campo da Manguela, AZIAS Ponte da Barca",
      playAtHome: true,
    },
    team: {
      teamPlayingAtHome: "Azias FC",
      teamPlayingAtHomeLogo: "/azias-fc-logo.png",
      teamPlayingAway: "FC Azias",
      teamPlayingAwayLogo: "/azias-fc-logo.png",
    },
    results: {
      teamPlayingAtHomeScore: 2,
      teamPlayingAwayScore: 1,
    },
  },
  {
    id: 8,
    match: {
      championship: "Liga INATEL",
      jornada: 9,
      date: "Domingo, 14 Dezembro 2025",
      hour: "12:00",
      address: "Campo da Manguela, AZIAS Ponte da Barca",
      playAtHome: true,
    },
    team: {
      teamPlayingAtHome: "Azias FC",
      teamPlayingAtHomeLogo: "/azias-fc-logo.png",
      teamPlayingAway: "FC Azias",
      teamPlayingAwayLogo: "/azias-fc-logo.png",
    },
    results: {
      teamPlayingAtHomeScore: 2,
      teamPlayingAwayScore: 1,
    },
  },
  {
    id: 9,
    match: {
      championship: "Liga INATEL",
      jornada: 10,
      date: "Domingo, 14 Dezembro 2025",
      hour: "12:00",
      address: "Campo da Manguela, AZIAS Ponte da Barca",
      playAtHome: true,
    },
    team: {
      teamPlayingAtHome: "Azias FC",
      teamPlayingAtHomeLogo: "/azias-fc-logo.png",
      teamPlayingAway: "FC Azias",
      teamPlayingAwayLogo: "/azias-fc-logo.png",
    },
    results: {
      teamPlayingAtHomeScore: 2,
      teamPlayingAwayScore: 1,
    },
  },
  {
    id: 10,
    match: {
      championship: "Liga INATEL",
      jornada: 11,
      date: "Domingo, 14 Dezembro 2025",
      hour: "12:00",
      address: "Campo da Manguela, AZIAS Ponte da Barca",
      playAtHome: true,
    },
    team: {
      teamPlayingAtHome: "Azias FC",
      teamPlayingAtHomeLogo: "/azias-fc-logo.png",
      teamPlayingAway: "FC Azias",
      teamPlayingAwayLogo: "/azias-fc-logo.png",
    },
    results: {
      teamPlayingAtHomeScore: 2,
      teamPlayingAwayScore: 1,
    },
  },
  {
    id: 11,
    match: {
      championship: "Liga INATEL",
      jornada: 12,
      date: "Domingo, 14 Dezembro 2025",
      hour: "12:00",
      address: "Campo da Manguela, AZIAS Ponte da Barca",
      playAtHome: true,
    },
    team: {
      teamPlayingAtHome: "Azias FC",
      teamPlayingAtHomeLogo: "/azias-fc-logo.png",
      teamPlayingAway: "FC Azias",
      teamPlayingAwayLogo: "/azias-fc-logo.png",
    },
    results: {
      teamPlayingAtHomeScore: 2,
      teamPlayingAwayScore: 1,
    },
  },
  {
    id: 12,
    match: {
      championship: "Liga INATEL",
      jornada: 13,
      date: "Domingo, 14 Dezembro 2025",
      hour: "12:00",
      address: "Campo da Manguela, AZIAS Ponte da Barca",
      playAtHome: true,
    },
    team: {
      teamPlayingAtHome: "Azias FC",
      teamPlayingAtHomeLogo: "/azias-fc-logo.png",
      teamPlayingAway: "FC Azias",
      teamPlayingAwayLogo: "/azias-fc-logo.png",
    },
    results: {
      teamPlayingAtHomeScore: 2,
      teamPlayingAwayScore: 1,
    },
  },
];

export const Goalkeepers = [
  {
    id: 1,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Leandro",
    number: 1,
    age: 23,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 2,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Koké",
    number: 2,
    age: 31,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
];

export const Defenders = [
  {
    id: 1,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Marcus",
    number: 0,
    age: 38,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 2,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Pura Jr",
    number: 0,
    age: 19,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 3,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Russo",
    number: 0,
    age: 45,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 4,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Pura",
    number: 0,
    age: 24,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 5,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Berna",
    number: 0,
    age: 22,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 6,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Vitor",
    number: 0,
    age: 22,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 7,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Miguel",
    number: 0,
    age: 21,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
];

export const Midfielders = [
  {
    id: 1,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Nuno",
    number: 0,
    age: 22,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 2,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Cardoso",
    number: 0,
    age: 26,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 3,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Vitor",
    number: 0,
    age: 31,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 4,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Luis Dias",
    number: 0,
    age: 22,
    isCaptain: true,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 5,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Pedro",
    number: 0,
    age: 25,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 6,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Zé Duarte",
    number: 0,
    age: 29,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 7,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Mario",
    number: 0,
    age: 28,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 8,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Rato",
    number: 0,
    age: 39,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
];

export const Forwards = [
  {
    id: 1,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Ricardo",
    number: 0,
    age: 35,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 2,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Rafa",
    number: 0,
    age: 22,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 3,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Tiago",
    number: 0,
    age: 27,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 4,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Vivas",
    number: 0,
    age: 29,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 5,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Telmo",
    number: 0,
    age: 33,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 6,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Henrique",
    number: 0,
    age: 40,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 7,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Fernando",
    number: 0,
    age: 55,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 8,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Gil",
    number: 0,
    age: 31,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 9,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Daniel Sa",
    number: 0,
    age: 31,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 10,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Pedro",
    number: 0,
    age: 22,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
];

export const Coaches = [
  {
    id: 1,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Agostinho Costa",
    number: 0,
    age: null,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
  {
    id: 2,
    imageUrl: "/images/players/player-exemple.jpg",
    name: "Alexandre Neiva",
    number: 0,
    age: null,
    isCaptain: false,
    stats: { matches: 0, goals: 0, assists: 0 },
  },
];
